"""Add medical library models

Revision ID: 74e675197637
Revises: 2872d2ae6349
Create Date: 2026-06-05 18:48:44.954541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e675197637'
down_revision: Union[str, None] = '2872d2ae6349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_rules_employer_id'), 'clinical_rules', ['employer_id'], unique=False)
    op.create_index(op.f('ix_clinical_rules_id'), 'clinical_rules', ['id'], unique=False)
    op.create_table('diagnostic_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('motif', sa.String(length=100), nullable=False),
    sa.Column('vitality', sa.String(length=100), nullable=True),
    sa.Column('percussion', sa.String(length=100), nullable=True),
    sa.Column('palpation', sa.String(length=100), nullable=True),
    sa.Column('radiology', sa.String(length=100), nullable=True),
    sa.Column('lesion_duration', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.JSON(), nullable=False),
    sa.Column('treatment_plan', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_templates_employer_id'), 'diagnostic_templates', ['employer_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_templates_id'), 'diagnostic_templates', ['id'], unique=False)
    op.create_table('medicaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('forme', sa.String(length=100), nullable=True),
    sa.Column('posologie_default', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('substitution_allergie', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicaments_employer_id'), 'medicaments', ['employer_id'], unique=False)
    op.create_index(op.f('ix_medicaments_id'), 'medicaments', ['id'], unique=False)
    op.create_index(op.f('ix_medicaments_name'), 'medicaments', ['name'], unique=False)
    op.drop_constraint(op.f('actes_patient_id_fkey'), 'actes', type_='foreignkey')
    op.drop_constraint(op.f('actes_praticien_id_fkey'), 'actes', type_='foreignkey')
    op.create_foreign_key(None, 'actes', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actes', 'users', ['praticien_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cabinet_configs', 'use_letterhead',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_cabinet_configs_clinic_id'), 'cabinet_configs', ['clinic_id'], unique=False)
    op.drop_constraint(op.f('catalog_acts_specialty_id_fkey'), 'catalog_acts', type_='foreignkey')
    op.create_foreign_key(None, 'catalog_acts', 'specialties', ['specialty_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cephalo_analyses_patient_id_fkey'), 'cephalo_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'cephalo_analyses', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('clinical_protocols_category_id_fkey'), 'clinical_protocols', type_='foreignkey')
    op.create_foreign_key(None, 'clinical_protocols', 'clinical_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_act_correlations_doctor_id_fkey'), 'doctor_act_correlations', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_act_correlations', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_act_habits_doctor_id_fkey'), 'doctor_act_habits', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_act_habits', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_medication_habits_doctor_id_fkey'), 'doctor_medication_habits', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_medication_habits', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_prescription_preferences_doctor_id_fkey'), 'doctor_prescription_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_prescription_preferences', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctor_trigger_habits_doctor_id_fkey'), 'doctor_trigger_habits', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_trigger_habits', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_archives_patient_id_fkey'), 'document_archives', type_='foreignkey')
    op.create_foreign_key(None, 'document_archives', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dossiers_cliniques_patient_id_fkey'), 'dossiers_cliniques', type_='foreignkey')
    op.create_foreign_key(None, 'dossiers_cliniques', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('panoramic_analyses_patient_id_fkey'), 'panoramic_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'panoramic_analyses', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pathologies_specialty_id_fkey'), 'pathologies', type_='foreignkey')
    op.create_foreign_key(None, 'pathologies', 'specialties', ['specialty_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('treatment_master_plans_patient_id_fkey'), 'treatment_master_plans', type_='foreignkey')
    op.create_foreign_key(None, 'treatment_master_plans', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_master_plans', type_='foreignkey')
    op.create_foreign_key(op.f('treatment_master_plans_patient_id_fkey'), 'treatment_master_plans', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'pathologies', type_='foreignkey')
    op.create_foreign_key(op.f('pathologies_specialty_id_fkey'), 'pathologies', 'specialties', ['specialty_id'], ['id'])
    op.drop_constraint(None, 'panoramic_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('panoramic_analyses_patient_id_fkey'), 'panoramic_analyses', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'dossiers_cliniques', type_='foreignkey')
    op.create_foreign_key(op.f('dossiers_cliniques_patient_id_fkey'), 'dossiers_cliniques', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'document_archives', type_='foreignkey')
    op.create_foreign_key(op.f('document_archives_patient_id_fkey'), 'document_archives', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'doctor_trigger_habits', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_trigger_habits_doctor_id_fkey'), 'doctor_trigger_habits', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_prescription_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_prescription_preferences_doctor_id_fkey'), 'doctor_prescription_preferences', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_medication_habits', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_medication_habits_doctor_id_fkey'), 'doctor_medication_habits', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_act_habits', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_act_habits_doctor_id_fkey'), 'doctor_act_habits', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_act_correlations', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_act_correlations_doctor_id_fkey'), 'doctor_act_correlations', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'clinical_protocols', type_='foreignkey')
    op.create_foreign_key(op.f('clinical_protocols_category_id_fkey'), 'clinical_protocols', 'clinical_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'cephalo_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('cephalo_analyses_patient_id_fkey'), 'cephalo_analyses', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'catalog_acts', type_='foreignkey')
    op.create_foreign_key(op.f('catalog_acts_specialty_id_fkey'), 'catalog_acts', 'specialties', ['specialty_id'], ['id'])
    op.drop_index(op.f('ix_cabinet_configs_clinic_id'), table_name='cabinet_configs')
    op.alter_column('cabinet_configs', 'use_letterhead',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'actes', type_='foreignkey')
    op.drop_constraint(None, 'actes', type_='foreignkey')
    op.create_foreign_key(op.f('actes_praticien_id_fkey'), 'actes', 'users', ['praticien_id'], ['id'])
    op.create_foreign_key(op.f('actes_patient_id_fkey'), 'actes', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_medicaments_name'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_id'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_employer_id'), table_name='medicaments')
    op.drop_table('medicaments')
    op.drop_index(op.f('ix_diagnostic_templates_id'), table_name='diagnostic_templates')
    op.drop_index(op.f('ix_diagnostic_templates_employer_id'), table_name='diagnostic_templates')
    op.drop_table('diagnostic_templates')
    op.drop_index(op.f('ix_clinical_rules_id'), table_name='clinical_rules')
    op.drop_index(op.f('ix_clinical_rules_employer_id'), table_name='clinical_rules')
    op.drop_table('clinical_rules')
    # ### end Alembic commands ###
